### ISSUE TITLE
Whitespace to next paragraph/header missing

### ISSUE THREAD

**Issue by fthommen** [chang-zhao/dokuwiki-tree#2]
Hi,

I like this treestyle.  One little problem arises nevertheless: The old tree style left some whitespace before the next paragraph/heading:
![treetest_old_tree](https://user-images.githubusercontent.com/279232/56144360-890a3900-5fa2-11e9-843b-e1919791453b.png)

while the new style doesn't:
![treetest_new_tree](https://user-images.githubusercontent.com/279232/56144359-8871a280-5fa2-11e9-9452-ab3abf4ca538.png)

which is typographically less nice and reduces readibility.  This forces us to use hardcoded empty lines after each tree, which is somehow cumbersome.

We use the default dokuwiki template of Release 2018-04-22b "Greebo"

Is there a way to fix this?

Thanks in advance
Frank

**Comment by chang-zhao** [comment]
Hi Frank,
for some reason I had in CSS

```ul.idx {
   margin: 0;
}```

I think I will remove this "margin: 0;", and then it will have usual margins.

Also you can add to your CSS some other margin values if you like.

**Comment by fthommen** [comment]
Thank you very much for this very quick response.  For the time being I have just commented it out.  That works fine for us.

**Comment by chang-zhao** [comment]
I updated the CSS files. Thank you for helping to improve this, and for your work in general.
Good luck!
